### ISSUE TITLE
ArticleManager->getMostPopular() query saturates database capacity under load

### ISSUE THREAD

**Issue by LichP** [FelixOnline/Core#40]
Query in question starts on line 44 of src/FelixOnline/Core/ArticleManager.php, and looks like this:

```
SELECT
DISTINCT av_id AS id,
COUNT(av_id) AS c
FROM (
	SELECT av.article AS av_id FROM article_visit AS av
	INNER JOIN article AS a
		ON (av.article=a.id)
	INNER JOIN article_publication AS ap
		ON a.id = ap.article
		AND ap.republished = 0
		AND ap.publication_date >= NOW() - INTERVAL 3 WEEK
		AND ap.publication_date <= NOW()
		AND ap.deleted = 0
	ORDER BY timestamp DESC LIMIT 500
) AS t GROUP BY id ORDER BY c DESC LIMIT %i
```

During recent load spikes on dougal I've observed large numbers of instances of this query (like 100+) taking huge amounts of time to complete (many running to over 1000 seconds), which have to be killed en masse in order to recover the server. While running a single instance of the query does not appear to be problematic, it seems that enough instances of the query start running in a short period, the snowball affect kicks in and quickly saturates CPU capacity on the server. 

Initial diagnosis suggested the lack of a specific index for av.article on the article_visit table was the main problem, as this table has over 4 million rows and joining against this column without an index would be expensive. Adding an index for this column helped, but has not solved the problem. It looks like the derived table that must be made for the inner query is too expensive. The following query is somewhat more efficient, but loses the `ORDER BY timestamp LIMIT 500` for finding only the most recent relevant rows of article_visit:

```
SELECT av.article AS id, COUNT(av.article) AS c
FROM article_visit AS av
WHERE av.article IN (
	SELECT a.id FROM article a
	INNER JOIN article_publication AS ap
		ON a.id = ap.article
		AND ap.republished = 0
		AND ap.publication_date >= NOW() - INTERVAL 3 WEEK
		AND ap.publication_date <= NOW()
		AND ap.deleted = 0
) GROUP BY av.article ORDER BY c DESC
```

This query runs much faster (0.2s when server was under load and the original query was taking around 3 minutes), and currently produces the same result, however this won't be true when the total visits for articles published in the past three weeks exceeds 500, so an alternative strategy may be needed.

**Comment by LichP** [comment]
One possibility might be to switch from a fixed size variable time sample (i.e. 500 most recent visits to relevant articles) to a fixed time variable size sample (i.e. all visits to relevant articles in the past 24 hours). This could be accomplished with a timestamp where clause on the new query:

```
SELECT av.article AS id, COUNT(av.article) AS c
FROM article_visit AS av
WHERE av.article IN (
	SELECT a.id FROM article a
	INNER JOIN article_publication AS ap
		ON a.id = ap.article
		AND ap.republished = 0
		AND ap.publication_date >= NOW() - INTERVAL 3 WEEK
		AND ap.publication_date <= NOW()
		AND ap.deleted = 0
)
AND av.timestamp >= NOW() - INTERVAL 24 HOUR
GROUP BY av.article ORDER BY c DESC
```

**Comment by LichP** [comment]
I've just tested the query during a load event where we've got 60+ instances of the original query running (most for over five minutes). The new query runs in 1 to 1.5 seconds in these conditions.

**Comment by lsproc** [comment]
Thanks @LichP. Actually what has happened in respect to the server load is Felix Online has been running with caching disabled due to a permissions error on Dougal which prevented the caches building.

This has now been fixed so this problem would go away. The result from the query is maintained for a period of time (I want to say a few hours) before it is rebuilt so it should avoid the server falling over.

That being said, this is a pretty rubbish query so I will replace it. Another option would be to consider visits from all time, and do what the BBC does to "mitigate" against old articles floating up which is to put the publication date below the title for older articles. I'll have a think and will make an appropriate change.

I do think however that the server should not be falling over with a query like this. Perhaps you/Pete needs to take a look at the MySQL configuration/move over to the new servers!

**Comment by LichP** [comment]
I am a bit suspicious of something in the MySQL config contributing to this. The original query performs well enough in isolation, and I don't have a good understanding of how the snowballing effect gets started. The only thing I have observed is that simply killing the runaway processes isn't enough: the server clearly needs a little bit of time to reclaim resources or perform cleanup, as new queries coming in immediately after a mass cull of runaway processes will continue to stall in the 'Sending data' phase until enough time has passed, requiring several passes of process killing before things get back to normal.

**Comment by lsproc** [comment]
There is something to be said of the php setup being a contributing factor. Might be better to discuss this offline, I'll drop you an email.
